
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: veiculo
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: veiculo/v3/api-docs